version: '3.7'

networks:
  backend:
    driver: bridge

services:
  headless-browser:
    container_name: headless-browser
    build: ../build/docker/headless-browser
    shm_size: 1g # increased to show yahoo.com
    networks:
      - backend

  workspace:
    container_name: workspace
    build: ../build/docker/go
    tty: true
    volumes:
      - ../:/go/src/work
    depends_on:
      - headless-browser
    networks:
      - backend
