CREATE TABLE t_pages (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    href VARCHAR(255),
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
