version: '3.7'

networks:
  backend:
    driver: bridge

services:
  headless-browser:
    container_name: headless-browser
    build: ./headless-browser
    shm_size: 512m # increased to show yahoo.com
    networks:
      - backend

  workspace:
    container_name: workspace
    build: ./go
    tty: true
    volumes:
      - ../code/go:/go/src/work
    depends_on:
      - headless-browser
    networks:
      - backend
